version: '3.0' # Compose file version

services:
  mysterium-proxy: # Service name
    
    image: mysteriumnetwork/myst:latest # Docker image
    
    ports: # Exposes ports to the host machine.
      - 44449:44449 # http://localhost:44449 - Mysterium Node UI access 
      - 4050:4050 # http://localhost:4050 - TequilAPI access
      - 40001:40001 # http://localhost:40001 - Unspecified usage 
    
    cap_add: # Adds Linux capabilities.
      - NET_ADMIN # The Linux NET_ADMIN capability is required for creating VPN tunnels.

    command: '--tequilapi.auth.username=${TEQUILAPI_USERNAME} --tequilapi.auth.password=${TEQUILAPI_PASSWORD} --tequilapi.address=0.0.0.0 --tequilapi.port=4050 --ui.port=44449 --proxymode daemon' # Specifies the command to execute when the container starts. This command starts the Mysterium node with specific parameters for the TequilAPI and the UI.

    volumes: # Mounts host paths or named volumes.
      - ./myst-data:/var/lib/Mysterium-node # Maps data storage # Maps the 'myst-data' directory from the host to '/var/lib/Mysterium-node' inside the container. This is where the Mysterium node stores its data.